# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Critically Open Neuroscience
tagline:          'A Div III + some'
description:      'An open lab notebook and writing space for a Division III @ Hampshire College.'
url:              http://kathleenleeper.github.io
baseurl:          '/'
paginate:         5

author :
  name : Kathleen Leeper
  firstName: Kathleen
  familyName: Leeper
  email : kathleen.leeper@gmail.com
  github : kathleenleeper

production_url : http://kathleenleeper.github.io

github:
  repo:           https://github.com/kathleenleeper/
